import type { DocsBundle } from "./schema";

export const demoBundle: DocsBundle = {
  schemaVersion: 1,
  project: {
    name: "Pawprint API",
    description: "A tiny API for the world’s most documented pets.",
    accent: "#ff6b4a",
  },
  generatedAt: "2026-07-19T00:00:00.000Z",
  generator: { name: "codex", model: "gpt-5.6" },
  navigation: [
    {
      label: "Start here",
      items: [
        { label: "Introduction", slug: "introduction" },
        { label: "Authentication", slug: "authentication" },
      ],
    },
    {
      label: "Endpoints",
      items: [
        { label: "List pets", slug: "api/list-pets" },
        { label: "Create a pet", slug: "api/create-pet" },
      ],
    },
  ],
  pages: [
    {
      slug: "introduction",
      title: "Build something pawsome",
      description: "Everything you need to make your first Pawprint API call.",
      sourceFiles: ["openapi.yaml", "src/routes/pets.ts"],
      markdown: `# Build something pawsome

The Pawprint API gives you a small, friendly surface for managing pets. This documentation bundle was generated by **Codex** from the API contract and route implementation, then published to Smolify.

## Your first request

Use the public sandbox without creating an account:

\`\`\`bash
curl https://api.pawprint.test/v1/pets
\`\`\`

## What Codex checked

- Routes against the OpenAPI contract
- Authentication requirements
- Request and response examples
- Error branches in the source implementation

> Generated docs should still be reviewed like code. The Smolify skill leaves the Markdown in your repository so every change is visible in git.
`,
    },
    {
      slug: "authentication",
      title: "Authentication",
      description: "Authenticate server-to-server requests with a bearer token.",
      sourceFiles: ["src/middleware/auth.ts"],
      markdown: `# Authentication

Send your API token in the \`Authorization\` header.

## Bearer token

\`\`\`http
Authorization: Bearer pp_live_example
\`\`\`

Tokens are secrets. Keep them out of browser code and source control.
`,
    },
    {
      slug: "api/list-pets",
      title: "List pets",
      description: "Return the pets visible to the current account.",
      sourceFiles: ["src/routes/pets.ts#L12-L38"],
      markdown: `# List pets

\`GET /v1/pets\` returns a paginated collection.

## Request

\`\`\`bash
curl https://api.pawprint.test/v1/pets \\
  -H "Authorization: Bearer $PAWPRINT_TOKEN"
\`\`\`

## Response

\`\`\`json
{"data":[{"id":"pet_01","name":"Mochi","species":"cat"}],"next":null}
\`\`\`
`,
    },
    {
      slug: "api/create-pet",
      title: "Create a pet",
      description: "Add a pet to the current account.",
      sourceFiles: ["src/routes/pets.ts#L40-L82", "src/schemas/pet.ts"],
      markdown: `# Create a pet

\`POST /v1/pets\` creates a pet.

## Request body

| Field | Type | Required |
| --- | --- | --- |
| \`name\` | string | yes |
| \`species\` | \`cat\` or \`dog\` | yes |

## Example

\`\`\`bash
curl -X POST https://api.pawprint.test/v1/pets \\
  -H "Authorization: Bearer $PAWPRINT_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{"name":"Mochi","species":"cat"}'
\`\`\`
`,
    },
  ],
};
