import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { renderMarkdown } from "@/lib/docs/markdown";
import { getDocsBundle } from "@/lib/docs/repository";
import { BrandMark } from "@/components/brand";

type PageProps = {
  params: Promise<{ project: string; slug?: string[] }>;
};

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { project, slug } = await params;
  const bundle = await getDocsBundle(project);
  const page = bundle?.pages.find((item) => item.slug === (slug?.join("/") || "introduction"));
  return page ? { title: page.title, description: page.description } : {};
}

export default async function DocsPage({ params }: PageProps) {
  const { project, slug } = await params;
  const bundle = await getDocsBundle(project);
  if (!bundle) notFound();

  const currentSlug = slug?.join("/") || "introduction";
  const page = bundle.pages.find((item) => item.slug === currentSlug);
  if (!page) notFound();
  const rendered = await renderMarkdown(page.markdown);

  return (
    <div className="docs-shell" style={{ "--accent": bundle.project.accent } as React.CSSProperties}>
      <header className="docs-header">
        <Link href={`/${project}/introduction`} className="docs-brand"><span>{bundle.project.name.slice(0, 1)}</span>{bundle.project.name}</Link>
        <div className="docs-search"><kbd>⌘ K</kbd><span>Search documentation</span></div>
        <a className="github-link" href="https://github.com" aria-label="GitHub">GitHub ↗</a>
      </header>
      <aside className="docs-sidebar">
        <p className="powered-by"><BrandMark compact />Hosted by Smolify</p>
        {bundle.navigation.map((group) => (
          <nav key={group.label}>
            <h2>{group.label}</h2>
            {group.items.map((item) => (
              <Link key={item.slug} href={`/${project}/${item.slug}`} data-active={item.slug === currentSlug}>{item.label}</Link>
            ))}
          </nav>
        ))}
      </aside>
      <main className="docs-main">
        <div className="page-kicker">{page.description}</div>
        <article className="prose" dangerouslySetInnerHTML={{ __html: rendered.html }} />
        <footer className="source-note">Generated by {bundle.generator.name} with {bundle.generator.model} · {page.sourceFiles.length} source {page.sourceFiles.length === 1 ? "file" : "files"}</footer>
      </main>
      <aside className="docs-toc">
        <h2>On this page</h2>
        {rendered.tableOfContents.map((item) => <a key={item.id} href={`#${item.id}`} data-depth={item.depth}>{item.label}</a>)}
      </aside>
    </div>
  );
}
